### ISSUE TITLE
Extend slack_send_message() to allow custom text

### ISSUE THREAD

**Issue by joelsdc** [arsperger/kamailio-slack#1]
Hello!

I was wondering if you had planned adding the possibility of sending custom text to slack?

(This would be request independent not tied to **MESSAGE** type)

For example:

```
request_route() {
...
	# Send custom MSG to slack
		slack_send_message("Something custom I want to post to slack");
	}
...
```

Thanks!

**Comment by arsperger** [comment]
Hi, yes, I have it in the TODO: `implement function to send msg from any route for notification purposes.`

I think to add evaluation of pseudo-variables as well. 

Thanks for your interest.

**Comment by joelsdc** [comment]
Cool! if you need help testing feel free to ping me!

**Comment by arsperger** [comment]
hi, 
new function is ready `slack_send_log` it works from any route and can evaluate pv.
